### ISSUE TITLE
Install error of missing password

### ISSUE THREAD

**Issue by Fetkou** [HKU-Smart-Mobility-Lab/map-boardcast#1]
Hi, I am trying to run your broadcast. I am not familiar with Javascript, just want to take a look. I installed Node.js and ran "npm install", error occurred as below. Can I resolve it? Thank you.

npm notice
npm notice New minor version of npm available! 10.2.4 -> 10.5.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.5.0
npm notice Run npm install -g npm@10.5.0 to update!
npm notice
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR!
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login

npm ERR! A complete log of this run can be found in: C:\Users\Admin\AppData\Local\npm-cache\_logs\2024-03-23T14_57_42_554Z-debug-0.log

**Comment by Matthewow** [comment]
Hi there, you could remove the `package-lock.json`, then `npm install`

**Comment by Fetkou** [comment]
Thank you for your prompt reply! 
The webpage is open correctly. There are tags on the left top of the page. But I can't see the map, the page is empty, LOL.
![image](https://github.com/HKU-Smart-Mobility-Lab/map-boardcast/assets/38153105/1711b9e0-9130-497e-a51a-f53af0420084)

**Comment by Matthewow** [comment]
Hi @Fetkou, this is because the Mapbox token is not valid anymore, I also added some guidance in the Readme section. Please refer to it, `git pull` again, and add your token to the `.env` file, it will be working. Let me know if there's still further issues.

**Comment by Fetkou** [comment]
Hi, thank you for your guidance, but this time I didn't see anything on the page, even the tags. All I have done is git clone again, and add the Access Token in the .env. I didn't modify anything elsewhere. I don't know what happened.

PORT=3001
REACT_APP_MAPBOX_ACCESS_TOKEN='pk.eyJ1IjoiODE1Mjc2MzI0IiwiYSI6ImNsdTVuNDdxNjFwaTc...'

**Comment by Matthewow** [comment]
@Fetkou Have you added your data as the Readme suggests? Or you can check out to develop branch to see some testing data there
